### ISSUE TITLE
[Challenge 001] Meetup page gallery animation

### ISSUE THREAD

**Issue by MrSunshyne** [Front-End-Coders-Mauritius/frontendmu-astro#30]
The challenge is to display the photos in a fun way on the meetup event page above the fold. 

Here's the figma: 
https://www.figma.com/file/PZQmtrZMYF2Vy9gqLJMAM7/Gallery-Animation-on-Meetup-Page?node-id=0%3A1&t=k3sW2Xjucj8GGkVb-1

Here are some guides. You can attempt just the first one or all of them !

- Display 3 images in the 3 blocks
- Animate them into position
- Cycle through the available images
- Animate the blocks themselves
- Hover animation

Comment for any questions or to let everyone know you're attempting the challenge. Have fun 

Good luck!

**Comment by MrSunshyne** [comment]
My attempt is in progress here: https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/pull/36

**Comment by mahima98** [comment]
My attempt here - WIP : #40

**Comment by Aurazor** [comment]
My attempt - #39

**Comment by MrSunshyne** [comment]
challenge complete
