### ISSUE TITLE
Footer Alignment issue on About Page

### ISSUE THREAD

**Issue by yaasir007** [Front-End-Coders-Mauritius/frontendmu-astro#47]
<img width="1385" alt="fullwisth" src="https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/77941119/2f462876-5505-4db1-8d31-7fac340d2d30">
<img width="1380" alt="mobile" src="https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/77941119/29c38389-67db-4ea7-99a3-ab2b073e8f37">

Both on big screen and on mobile

**Comment by MrSunshyne** [comment]
thanks for the fix !
