### ISSUE TITLE
Implementation of authentication + RSVP to meetups

### ISSUE THREAD

**Issue by nicolasstrands** [Front-End-Coders-Mauritius/frontendmu-astro#56]
As discussed with @MrSunshyne, we are implementing authentication on the website so that users could sign up/sign in and submit RSVPs to meetups they are attending. The information would be stored on a database so it'd remember which user RSVP'd for which event.

There will also be a profile page for each user where we could store metadata about the user (current occupation, veg/non-veg, etc)

We are using Supabase to handle Authentication + Database

**Comment by MrSunshyne** [comment]
You did it ! closing
